# Generated by Django 5.1.5 on 2026-06-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='theatres.order'),
        ),
        migrations.AddField(
            model_name='performance',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='theatres.hall'),
        ),
        migrations.AddField(
            model_name='performance',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='theatres.play'),
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theatres.hall'),
        ),
        migrations.AddField(
            model_name='play',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='theatres.theatre'),
        ),
        migrations.AddField(
            model_name='hall',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='theatres.theatre'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatres.performance'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatres.seat'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='theatres.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('play', 'hall', 'date', 'time')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'number', 'hall')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'seat')},
        ),
    ]
